version: '2.4'
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: academy
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: